AWSTemplateFormatVersion: 2010-09-09

Transform: AWS::Serverless-2016-10-31

Description: Twitter Analytics Api

Parameters:

  Environment:
    Type: String
    Description: Set the deployment environment.
    AllowedValues:
      - Development
      - Staging
      - Production

  JwtSecret:
    Type: String
    Description: Set secret token JWT

Mappings:
  StageNameMap:
    Development:
      StageName: dev
    Staging:
      StageName: stg
    Production:
      StageName: prod
  EnvironmentToPathBaseMap:
    Development:
      PathBase: /development
    Staging:
      PathBase: /staging
    Production:
      PathBase: /

Globals:
  Api:
    OpenApiVersion: 3.0.1

Resources:
  DynamoDBTable:
    Type: AWS::DynamoDB::Table
    DeletionPolicy: Retain
    Properties:
      TableName: twitter-analytics-v2
      KeySchema:
        - AttributeName: PK
          KeyType: HASH
        - AttributeName: SK
          KeyType: RANGE
      AttributeDefinitions:
        - AttributeName: PK
          AttributeType: S
        - AttributeName: SK
          AttributeType: S
        - AttributeName: GSIPK
          AttributeType: S
        - AttributeName: GSISK
          AttributeType: S
      BillingMode: PAY_PER_REQUEST
      GlobalSecondaryIndexes:
      - IndexName: GSIIndex
        KeySchema:
        - AttributeName: GSIPK
          KeyType: HASH
        - AttributeName: GSISK
          KeyType: RANGE
        Projection:
          ProjectionType: ALL
      Tags:
        - Key: Name
          Value: twitter-analytics-v2-api:DynamoDB
